#!/usr/bin/lua

table.unpack = table.unpack or unpack

local PATH = arg[1] or ""

---@return Presentation?, string?
local function load_statscore_safely(path)
	local env = {}

	local get_statscore, err
	if setfenv then
		get_statscore, err = loadfile(path)
		get_statscore = get_statscore and setfenv(get_statscore, env)
	else
		get_statscore, err = loadfile(path, "t", env)
	end
	if not get_statscore then
		return nil, "Loading file failed: " .. err
	end

	local ok, res = pcall(get_statscore)
	if not ok then
		return nil, "Executing file failed: " .. tostring(res)
	end

	return res
end

local statscore, err = load_statscore_safely("/dev/shm/statscore.lua")
if not statscore then
	error(err)
end

for part in PATH:gmatch("[.]?([^.]+)") do
	statscore = statscore or {}
	statscore = statscore[tonumber(part)] or statscore[part]
end
print(statscore)
