#!/usr/bin/lua

table.unpack = table.unpack or unpack
local posix = require("posix")
local present = require("present")

local STATSCORE_PATH = "/dev/shm/statscore.lua"

local TICK_PERIOD = 4
local CPU_LOAD_PERIOD_TICKS = 1
local MEM_PERIOD_TICKS = 1
local ROOTFS_PERIOD_TICKS = 64
local TEMPS_PERIOD_TICKS = 8
local BATS_PERIOD_TICKS = 16
local NETFACES_PERIOD_TICKS = 2

---@param obj any
---@return string
local function serialize(obj)
	local t = type(obj)

	if t == "number" or t == "boolean" then
		if obj ~= obj then
			return "(0/0)"
		else
			return tostring(obj)
		end
	elseif t == "string" then
		return string.format("%q", obj)
	elseif t == "table" then
		local parts = {}
		for k, v in pairs(obj) do
			local kt = type(k)
			---@type string?
			local k_slzd = nil
			if kt == "number" or kt == "boolean" then
				k_slzd = "[" .. tostring(k) .. "]"
			elseif kt == "string" then
				if k:match("^[%w_][%w_%d]*$") then
					k_slzd = k
				else
					k_slzd = string.format("[%q]", k)
				end
			end

			if k_slzd then
				local serialized_v = serialize(v)
				parts[#parts + 1] = k_slzd .. " = " .. serialized_v
			else
				parts[#parts + 1] = "--[[unaccessible " .. kt .. " key]]"
			end
		end
		return "{ " .. table.concat(parts, ", ") .. " }"
	elseif t == "function" then
		return "function(...) return (...) end"
	else
		return "nil --[[unserializable " .. t .. "]]"
	end
end

---@type {fn: function, period: integer}[]
local score_sources = {
	{ fn = present.cpu, period = CPU_LOAD_PERIOD_TICKS },
	{ fn = present.mem, period = MEM_PERIOD_TICKS },
	{ fn = present.rootfs, period = ROOTFS_PERIOD_TICKS },
	{ fn = present.bats, period = BATS_PERIOD_TICKS },
	{ fn = present.temps, period = TEMPS_PERIOD_TICKS },
	{ fn = present.netfaces, period = NETFACES_PERIOD_TICKS },
}

local tick = 0
while true do
	for _, score_source in ipairs(score_sources) do
		if tick % score_source.period == 0 then
			score_source.fn()
		end
	end

	local f = io.open(STATSCORE_PATH, "w")
	if f then
		f:write("return " .. serialize(present.ation))
		f:close()
	end

	posix.sleep(TICK_PERIOD)
	tick = tick + 1
end
