#!/usr/bin/lua

table.unpack = table.unpack or unpack
local posix = require("posix")
local socket = require("posix.sys.socket")
local signal = require("posix.signal")

local present = require("present")

---@param t table?
---@param ... any
function table.get_in(t, ...)
	local keys = table.pack(...)
	for i = 1, keys.n do
		if t == nil then
			return
		end
		t = t[keys[i]]
	end
	return t
end

-----------------
--- constants ---
-----------------

HOME_DIR_PATH = os.getenv("HOME") or "~"
TMP_DIR_PATH = os.getenv("XDG_RUNTIME_DIR") or "/tmp"
CONFIG_PATHS = {
	os.getenv("STATSCORED_CONFIG") or (HOME_DIR_PATH .. "/.config/statscored.lua"),
	"/etc/statscored.lua",
}
SOCKET_PATH = TMP_DIR_PATH .. "/statscore.sock"

---------------------
--- serialization ---
---------------------

---@param n number|boolean
local function serialize_number_or_boolean(n)
	return n ~= n and "(0/0)" or -math.huge >= n and "(1/0)" or n >= math.huge and "(-1/0)" or tostring(n)
end

---@param s string
local function serialize_string(s)
	return string.format("%q", s)
end

---@param obj any
---@return string
local function serialize(obj)
	local t = type(obj)

	if t == "number" or t == "boolean" then
		return serialize_number_or_boolean(obj)
	elseif t == "string" then
		return serialize_string(obj)
	elseif t == "table" then
		local pairs_slzd = {}
		for k, v in pairs(obj) do
			local kt = type(k)

			---@type string?
			local k_slzd = nil
			if kt == "string" and k:match("^[%w_][%w_%d]*$") then
				k_slzd = k
			else
				if kt == "number" or kt == "boolean" then
					k_slzd = serialize_number_or_boolean(k)
				elseif kt == "string" then
					k_slzd = serialize_string(k)
				end
				k_slzd = k_slzd and "[" .. k_slzd .. "]"
			end

			pairs_slzd[#pairs_slzd + 1] = k_slzd and (k_slzd .. " = " .. serialize(v))
				or "--[[inaccessible " .. kt .. " key]]"
		end
		return "{ " .. table.concat(pairs_slzd, ", ") .. " }"
	elseif t == "function" then
		return "function(...) end"
	elseif t == "nil" then
		return "nil"
	else
		return "nil --[[unserializable " .. t .. "]]"
	end
end

--------------
--- config ---
--------------

---@class TickMultipliersConfig
---@field cpu_load integer
---@field mem integer
---@field fs integer
---@field bats integer
---@field temps integer
---@field netfaces integer

---@class Config
---@field tick_period number
---@field tick_multipliers TickMultipliersConfig

---@param paths string[]
---@return Config?, string?
local function load_config(paths)
	---@type Config
	local DEFAULT_CONFIG = {
		tick_period = 4,
		tick_multipliers = {
			cpu_load = 2,
			mem = 2,
			fs = 64,
			bats = 16,
			temps = 4,
			netfaces = 1,
		},
	}

	---@type function?, string?
	local get, err
	for _, path in pairs(paths) do
		local env = {}

		if setfenv then
			get, err = loadfile(path)
			get = get and setfenv(get, env)
		else
			get, err = loadfile(path, nil, env)
		end

		if get then
			break
		end
	end
	if not get then
		return  DEFAULT_CONFIG, err
	end

	local ok, res = pcall(get)
	if not ok then
		return nil, res
	end

	return {
		tick_period = table.get_in(res, "tick_period") or DEFAULT_CONFIG.tick_period,
		tick_multipliers = {
			cpu_load = table.get_in(res, "tick_multipliers", "cpu_load") or DEFAULT_CONFIG.tick_multipliers.cpu_load,
			mem = table.get_in(res, "tick_multipliers", "mem") or DEFAULT_CONFIG.tick_multipliers.mem,
			fs = table.get_in(res, "tick_multipliers", "fs") or DEFAULT_CONFIG.tick_multipliers.fd,
			bats = table.get_in(res, "tick_multipliers", "bats") or DEFAULT_CONFIG.tick_multipliers.bats,
			temps = table.get_in(res, "tick_multipliers", "temps") or DEFAULT_CONFIG.tick_multipliers.temps,
			netfaces = table.get_in(res, "tick_multipliers", "netfaces") or DEFAULT_CONFIG.tick_multipliers.netfaces,
		},
	}
end

------------
--- main ---
------------

local config = assert(load_config(CONFIG_PATHS))

---@type {fn: function, period: integer}[]
local score_sources = {
	{ fn = present.cpu_load, period = config.tick_multipliers.cpu_load },
	{ fn = present.mem, period = config.tick_multipliers.mem },
	{ fn = present.fs, period = config.tick_multipliers.fs },
	{ fn = present.bats, period = config.tick_multipliers.bats },
	{ fn = present.temps, period = config.tick_multipliers.temps },
	{ fn = present.netfaces, period = config.tick_multipliers.netfaces },
}

-- to make writing to broken pipe just report an error instead of crashing
signal.signal(signal.SIGPIPE, signal.SIG_IGN)

os.remove(SOCKET_PATH)
local server_fd = assert(socket.socket(socket.AF_UNIX, socket.SOCK_STREAM, 0))
assert(socket.bind(server_fd, { family = socket.AF_UNIX, path = SOCKET_PATH }))
assert(socket.listen(server_fd, 4))

local client_fds = {}

local fds = { [server_fd] = { events = { IN = true } } }
local tick = 0
while true do
	local is_connection_pending = posix.poll.poll(fds, config.tick_period * 1000) > 0
	if is_connection_pending then
		client_fds[#client_fds + 1] = socket.accept(server_fd)
	end

	for _, score_source in pairs(score_sources) do
		if score_source.period ~= 0 and tick % score_source.period == 0 then
			score_source.fn()
		end
	end

	for i, client_fd in pairs(client_fds) do
		local ok = socket.send(client_fd, "return " .. serialize(present.ation) .. "\n")
		if not ok then
			client_fds[i] = nil
		end
	end

	tick = tick + 1
end
